# Generated by Django 4.2.7 on 2026-06-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tutor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='location',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('orogun', 'Orogun'), ('samonda', 'Samonda')], default='', help_text='Physical location (for in-person sessions only).', max_length=20),
        ),
    ]
