# Generated by Django 4.2.7 on 2026-06-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tutor_name_timetableentry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
