# Generated by Django 4.2.7 on 2026-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_duration_course_external_id_course_is_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='manual_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='class',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='sessions_multi', to='core.topic'),
        ),
    ]
