# Generated by Django 4.2.7 on 2026-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_class_manual_topic_class_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
